import "../styles/globals.css";
import type { AppProps } from "next/app";
import "../styles/globals.css";
import { MoralisProvider } from "react-moralis";
import Head from "next/head";
import { NotificationProvider } from "@web3uikit/core";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <div>
            <Head>
                <title>EasyPe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <NotificationProvider>
                    <Component {...pageProps} />
                </NotificationProvider>
            </MoralisProvider>
        </div>
    );
}

export default MyApp;
